import { StyleSheet } from 'react-native';

const ticketFormStyles = StyleSheet.create({
    buttonContainer: {
        flexDirection: 'row',
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    button:{
        flex: 0,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        width: "80%",
        height: 50,
        backgroundColor: 'orange',
        borderRadius: 10,
        marginTop: 10,
    },
    buttonText:{
        fontSize: 30,
        fontFamily: 'Ubuntu-Bold',
        padding: 10,
        color: '#fff',
    },
    formCard: {
        backgroundColor: '#fff',
        borderRadius: 10,
        paddingLeft: 10,
        paddingRight: 10,
        paddingTop: 20,
        paddingBottom: 20,
        width: '100%',
        flexDirection: 'column',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
        marginTop: 25,
    },
    formCardHeader: {
        backgroundColor: '#fff',
        borderRadius: 10,
    },
    headerText: {
        fontSize: 40,
        fontFamily: 'Ubuntu-Bold',
        marginBottom: 30,
        width: '100%',
        textAlign: 'center',
        color: 'orange',
    },
    inputText: {
        flex: 1,
    },
    formInput: {   
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 0.5,
        borderColor: '#000',
        height: 50,
        borderRadius: 10,
        margin: 5,
    },
    inputIcon: {
        fontSize: 25,
        padding: 10,
    },
    inputLabel: {
        fontSize: 20,
        color: '#000',
        fontWeight: '700',
        textAlign: 'left',
        paddingLeft: 10,
    },
    btnContainer: {
        padding: 0,
    },
    datePicker: {
        width: '100%',
        height: 260,
        display: 'flex',
        alignItems: 'flex-start',
    },
    pickedDateContainer: {
        flexDirection: 'row',
        flex: 1,
        height: '100%',
    },
    pickedDate: {
        fontSize: 14,
        fontWeight: '400',
        color: 'black',
        textAlign: 'left',
        flex: 1,
        height: '100%',
        textAlignVertical: 'center',
    },
    formDateTime:{
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderWidth: 0.5,
        borderColor: '#000',
        height: 50,
        borderRadius: 10,
        margin: 5,
        flex: 0,
    },
    searchIcon: {
        fontSize: 25,
        fontWeight: 'bold',
        color: 'white',
    },
    customPlaceholder: {
        fontSize: 14,
        fontWeight: '400',
        color: 'black',
        textAlign: 'left',
        flex: 1,
        height: '100%',
        textAlignVertical: 'center',
        textTransform: 'capitalize',
    },
    modalTitle: {
        fontSize: 30,
        fontFamily: 'Ubuntu-Bold',
        marginBottom: 5,
        width: '100%',
        textAlign: 'center',
    },
    modalChoise: {
        margin: 20,
        backgroundColor: "white",
        borderRadius: 20,
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5
    },
    headerModalContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'orange',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        padding: 10,
        height: 50,
    },
    modalChoiseContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 10,
        padding: 10,
        // height: "100%",
    },
    choiseContainer: {
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: 50,
        margin: 5,
        borderColor: 'orange',
        borderWidth: 0.5,
        borderRadius: 10,
    },
    choisePelabuhanText: {
        fontSize: 20,
        textTransform: 'capitalize',
        textAlign: 'left',
        paddingLeft: 10,
        width: '100%',
        fontWeight: '500',
    },
    choiseText: {
        fontSize: 20,
        textTransform: 'capitalize',
        textAlign: 'left',
        paddingLeft: 10,
        width: '100%',
        fontWeight: '500',
    },
    choiseLokasiText: {
        fontSize: 14,
        textTransform: 'capitalize',
        textAlign: 'left',
        fontWeight: '400',
        width: '100%',
        paddingLeft: 10,
    },
});

export default ticketFormStyles;